
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // --- REGRAS PARA DESCONTO ---
  { id: 1, category: 'Desconto', text: 'Compra de R$ 500,00. Qual o desconto?', answers: ['R$ 50,00', 'NÃO TEM', 'R$ 20,00'], correctIndex: 1 },
  { id: 2, category: 'Desconto', text: 'Compra de R$ 800,00. Qual o desconto?', answers: ['R$ 50,00', 'NÃO TEM', 'R$ 100,00'], correctIndex: 0 },
  { id: 3, category: 'Desconto', text: 'Compra de R$ 1.100,00. Qual o desconto?', answers: ['R$ 100,00', 'R$ 50,00', 'NÃO TEM'], correctIndex: 1 },
  { id: 4, category: 'Desconto', text: 'Compra de R$ 1.300,00 A VISTA. Qual o desconto?', answers: ['R$ 50,00', 'R$ 50 + R$ 50', 'R$ 200,00'], correctIndex: 1 },
  { id: 5, category: 'Desconto', text: 'Compra de R$ 1.500,00 A VISTA.', answers: ['R$ 50 + R$ 50', 'R$ 50,00', 'NÃO TEM'], correctIndex: 0 },
  { id: 6, category: 'Desconto', text: 'Cliente comprou R$ 400,00.', answers: ['R$ 20,00', 'R$ 50,00', 'NÃO TEM'], correctIndex: 2 },
  { id: 7, category: 'Desconto', text: 'Cliente comprou R$ 600,00.', answers: ['NÃO TEM', 'R$ 50,00', 'R$ 10,00'], correctIndex: 0 },
  { id: 8, category: 'Desconto', text: 'Cliente comprou R$ 650,00.', answers: ['NÃO TEM', 'R$ 50,00', 'R$ 30,00'], correctIndex: 1 },
  { id: 9, category: 'Desconto', text: 'Compra de R$ 1.200,00.', answers: ['R$ 100,00', 'R$ 50,00', 'NÃO TEM'], correctIndex: 1 },
  { id: 10, category: 'Desconto', text: 'Compra de R$ 2.000,00 A VISTA.', answers: ['R$ 100 Fixos', 'R$ 50 + R$ 50', '5%'], correctIndex: 1 },

  // --- REGRAS PARA TRAVESSEIROS ---
  { id: 11, category: 'Travesseiro', text: 'Compra de R$ 500,00. Ganha travesseiro?', answers: ['SIM (1)', 'NÃO TEM', 'SIM (2)'], correctIndex: 1 },
  { id: 12, category: 'Travesseiro', text: 'Compra de R$ 700,00. Quantos travesseiros?', answers: ['1 TRAVESSEIRO', '2 TRAVESSEIROS', 'NENHUM'], correctIndex: 0 },
  { id: 13, category: 'Travesseiro', text: 'Compra de R$ 1.100,00. Quantos travesseiros?', answers: ['NENHUM', '1 TRAVESSEIRO', '2 TRAVESSEIROS'], correctIndex: 1 },
  { id: 14, category: 'Travesseiro', text: 'Compra de R$ 1.300,00. Quantos travesseiros?', answers: ['1 TRAVESSEIRO', '2 TRAVESSEIROS', '3 TRAVESSEIROS'], correctIndex: 1 },
  { id: 15, category: 'Travesseiro', text: 'Compra de R$ 2.500,00. Quantos travesseiros?', answers: ['4 TRAVESSEIROS', '1 TRAVESSEIRO', '2 TRAVESSEIROS'], correctIndex: 2 },
  { id: 16, category: 'Travesseiro', text: 'Compra de R$ 590,00.', answers: ['1 TRAVESSEIRO', 'NÃO TEM', '2 TRAVESSEIROS'], correctIndex: 1 },
  { id: 17, category: 'Travesseiro', text: 'Compra de R$ 650,00.', answers: ['1 TRAVESSEIRO', 'NÃO TEM', '2 TRAVESSEIROS'], correctIndex: 0 },
  { id: 18, category: 'Travesseiro', text: 'Compra de R$ 1.200,00.', answers: ['2 TRAVESSEIROS', '1 TRAVESSEIRO', 'NÃO TEM'], correctIndex: 1 },
  { id: 19, category: 'Travesseiro', text: 'Compra de R$ 1.250,00.', answers: ['1 TRAVESSEIRO', '2 TRAVESSEIROS', '3 TRAVESSEIROS'], correctIndex: 1 },
  { id: 20, category: 'Travesseiro', text: 'Compra de R$ 600,00 Exatos.', answers: ['NÃO TEM', '1 TRAVESSEIRO', '2 TRAVESSEIROS'], correctIndex: 0 },

  // --- VALOR DE FRETE ---
  { id: 21, category: 'Frete', text: 'Frete para BENEVIDES', answers: ['R$ 100,00', 'R$ 150,00', 'R$ 200,00'], correctIndex: 0 },
  { id: 22, category: 'Frete', text: 'Frete para SANTA ISABEL', answers: ['R$ 100,00', 'R$ 200,00', 'R$ 150,00'], correctIndex: 2 },
  { id: 23, category: 'Frete', text: 'Frete para SANTA BARBARA', answers: ['R$ 250,00', 'R$ 200,00', 'R$ 150,00'], correctIndex: 1 },
  { id: 24, category: 'Frete', text: 'Frete para MOSQUEIRO', answers: ['R$ 250,00', 'R$ 300,00', 'R$ 200,00'], correctIndex: 0 },
  { id: 25, category: 'Frete', text: 'Frete para SANTO A. TAUA', answers: ['R$ 250,00', 'R$ 300,00', 'R$ 350,00'], correctIndex: 1 },
  { id: 26, category: 'Frete', text: 'Frete para CASTANHAL', answers: ['R$ 300,00', 'R$ 400,00', 'R$ 350,00'], correctIndex: 2 },
  { id: 27, category: 'Frete', text: 'Frete para SÃO PAULO (Outras Cidades)', answers: ['R$ 500,00', 'VAMOS VERIFICAR', 'NÃO ENTREGAMOS'], correctIndex: 1 },
  { id: 28, category: 'Frete', text: 'Frete para MARITUBA (Outras Cidades)', answers: ['VAMOS VERIFICAR', 'R$ 50,00', 'GRÁTIS'], correctIndex: 0 },
  { id: 29, category: 'Frete', text: 'Frete BENEVIDES (Cartão)', answers: ['R$ 100,00', 'R$ 120,00', 'R$ 150,00'], correctIndex: 0 },
  { id: 30, category: 'Frete', text: 'Frete MOSQUEIRO (A Vista)', answers: ['R$ 200,00', 'R$ 250,00', 'R$ 300,00'], correctIndex: 1 },

  // --- VALORES DE COMISSÃO ---
  { id: 31, category: 'Comissão', text: 'Comissão Colchão Mola CASAL (188x138)', answers: ['R$ 50,00', 'R$ 100,00', 'R$ 150,00'], correctIndex: 1 },
  { id: 32, category: 'Comissão', text: 'Comissão Colchão Mola QUEEN (198x158)', answers: ['R$ 100,00', 'R$ 150,00', 'R$ 200,00'], correctIndex: 2 },
  { id: 33, category: 'Comissão', text: 'Comissão Colchão Mola S.KING (203x193)', answers: ['R$ 200,00', 'R$ 250,00', 'R$ 300,00'], correctIndex: 0 },
  { id: 34, category: 'Comissão', text: 'Comissão Conjunto Espuma SOLTEIRO', answers: ['R$ 50,00', 'R$ 30,00', 'R$ 20,00'], correctIndex: 0 },
  { id: 35, category: 'Comissão', text: 'Comissão Conjunto Espuma CASAL', answers: ['R$ 100,00', 'R$ 50,00', 'R$ 70,00'], correctIndex: 1 },
  { id: 36, category: 'Comissão', text: 'Comissão UNIBOX Solteiro (88cm)', answers: ['R$ 30,00', 'R$ 50,00', 'R$ 40,00'], correctIndex: 1 },
  { id: 37, category: 'Comissão', text: 'Comissão UNIBOX Solteirão (100cm)', answers: ['R$ 50,00', 'R$ 60,00', 'R$ 70,00'], correctIndex: 0 },
  { id: 38, category: 'Comissão', text: 'Comissão UNIBOX Casal (138cm)', answers: ['R$ 100,00', 'R$ 80,00', 'R$ 50,00'], correctIndex: 2 },
  { id: 39, category: 'Comissão', text: 'Comissão BICAMA Solteiro (88cm)', answers: ['R$ 50,00', 'R$ 70,00', 'R$ 30,00'], correctIndex: 0 },
  { id: 40, category: 'Comissão', text: 'Comissão BICAMA Solteirão (100cm)', answers: ['R$ 50,00', 'R$ 70,00', 'R$ 100,00'], correctIndex: 1 },
  { id: 41, category: 'Comissão', text: 'Comissão CABECEIRA (Qualquer tamanho)', answers: ['R$ 30,00', 'R$ 50,00', 'R$ 80,00'], correctIndex: 1 },
  { id: 42, category: 'Comissão', text: 'Comissão SOFÁ (Qualquer tamanho)', answers: ['R$ 50,00', 'R$ 100,00', 'R$ 80,00'], correctIndex: 2 },
  { id: 43, category: 'Comissão', text: 'Comissão Cama Mola Casal Padrão', answers: ['R$ 100,00', 'R$ 50,00', 'R$ 200,00'], correctIndex: 0 },
  { id: 44, category: 'Comissão', text: 'Comissão Cama Mola Queen Size', answers: ['R$ 250,00', 'R$ 200,00', 'R$ 150,00'], correctIndex: 1 },
  { id: 45, category: 'Comissão', text: 'Comissão Colchão Espuma D33 Casal', answers: ['R$ 100,00', 'R$ 80,00', 'R$ 50,00'], correctIndex: 2 },
  { id: 46, category: 'Comissão', text: 'Comissão Sofá Retrátil 2 Lugares', answers: ['R$ 80,00', 'R$ 100,00', 'R$ 150,00'], correctIndex: 0 },
  { id: 47, category: 'Comissão', text: 'Comissão Bicama Box Solteirão', answers: ['R$ 50,00', 'R$ 60,00', 'R$ 70,00'], correctIndex: 2 },
  { id: 48, category: 'Comissão', text: 'Comissão Unibox Casal Mola', answers: ['R$ 80,00', 'R$ 50,00', 'R$ 100,00'], correctIndex: 1 },
  { id: 49, category: 'Comissão', text: 'Comissão Cabeceira King', answers: ['R$ 50,00', 'R$ 80,00', 'R$ 100,00'], correctIndex: 0 },
  { id: 50, category: 'Comissão', text: 'Comissão Sofá de Canto', answers: ['R$ 50,00', 'R$ 120,00', 'R$ 80,00'], correctIndex: 2 },

  // --- ATENDIMENTO ---
  { id: 51, category: 'Atendimento', text: 'Cliente entrou na loja. O que fazer?', answers: ['IGNORAR', 'CUMPRIMENTAR', 'MEXER NO CELULAR'], correctIndex: 1 },
  { id: 52, category: 'Atendimento', text: 'Cliente reclamou do prazo de entrega.', answers: ['DISCUTIR', 'OUVIR E AJUDAR', 'CULPAR A FÁBRICA'], correctIndex: 1 },
  { id: 53, category: 'Atendimento', text: 'Cliente pediu desconto impossível.', answers: ['SER GROSSO', 'RIR DO CLIENTE', 'NEGOCIAR COM EDUCAÇÃO'], correctIndex: 2 },
  { id: 54, category: 'Atendimento', text: 'Cliente em dúvida entre dois colchões.', answers: ['APRESSAR', 'EXPLICAR BENEFÍCIOS', 'ESCOLHER O MAIS CARO'], correctIndex: 1 },
  { id: 55, category: 'Atendimento', text: 'Roupa do vendedor.', answers: ['CAMISA DO TIME', 'UNIFORME LIMPO', 'REGATA'], correctIndex: 1 },
  { id: 56, category: 'Atendimento', text: 'Cliente disse que vai "dar uma volta".', answers: ['FICAR COM RAIVA', 'DAR O CARTÃO', 'INSISTIR DEMAIS'], correctIndex: 1 },
  { id: 57, category: 'Atendimento', text: 'O que fideliza o cliente?', answers: ['PREÇO BAIXO', 'BOM ATENDIMENTO', 'BRINDE RUIM'], correctIndex: 1 },
  { id: 58, category: 'Atendimento', text: 'Cliente elogiou o atendimento.', answers: ['IGNORAR', 'AGRADECER', 'PEDIR GORJETA'], correctIndex: 1 },
  { id: 59, category: 'Atendimento', text: 'Produto chegou com defeito.', answers: ['RESOLVER RÁPIDO', 'IGNORAR MENSAGEM', 'DIZER QUE É NORMAL'], correctIndex: 0 },
  { id: 60, category: 'Atendimento', text: 'Como abordar o cliente?', answers: ['"E AÍ?"', '"POSSO AJUDAR?"', '"VAI COMPRAR?"'], correctIndex: 1 },
  
  // --- MAIS 50 PERGUNTAS DE ATENDIMENTO E VENDAS ---
  { id: 61, category: 'Atendimento', text: 'O cliente está apenas "olhando".', answers: ['IGNORAR', 'FICAR NA COLA', 'DEIXAR À VONTADE E FICAR ATENTO'], correctIndex: 2 },
  { id: 62, category: 'Atendimento', text: 'Cliente não gostou do preço.', answers: ['AGREGAR VALOR AO PRODUTO', 'BAIXAR PREÇO IMEDIATAMENTE', 'MANDAR IR NA CONCORRÊNCIA'], correctIndex: 0 },
  { id: 63, category: 'Atendimento', text: 'Uso de celular no salão.', answers: ['LIBERADO SEMPRE', 'SÓ PARA TRABALHO/CONSULTA', 'PARA REDES SOCIAIS'], correctIndex: 1 },
  { id: 64, category: 'Atendimento', text: 'Cliente entrou com sacola do concorrente.', answers: ['IGNORAR O CLIENTE', 'ATENDER NORMALMENTE', 'FALAR MAL DA OUTRA LOJA'], correctIndex: 1 },
  { id: 65, category: 'Atendimento', text: 'Cliente quer testar o colchão.', answers: ['NÃO DEIXAR', 'CONVIDAR A DEITAR', 'APENAS SENTAR'], correctIndex: 1 },
  { id: 66, category: 'Atendimento', text: 'Qual a melhor postura?', answers: ['ESCORADO NA PAREDE', 'SENTADO NO SOFÁ', 'EM PÉ E DISPONÍVEL'], correctIndex: 2 },
  { id: 67, category: 'Atendimento', text: 'Cliente indeciso com a cor do sofá.', answers: ['MOSTRAR FOTOS AMBIENTADAS', 'ESCOLHER POR ELE', 'DIZER QUE TUDO É IGUAL'], correctIndex: 0 },
  { id: 68, category: 'Atendimento', text: 'O que é Venda Adicional?', answers: ['VENDER O MAIS CARO', 'OFERECER ITEM COMPLEMENTAR', 'DAR DESCONTO'], correctIndex: 1 },
  { id: 69, category: 'Atendimento', text: 'Cliente pede prazo de entrega menor.', answers: ['PROMETER O IMPOSSÍVEL', 'VERIFICAR REAL POSSIBILIDADE', 'MENTIR SOBRE O ESTOQUE'], correctIndex: 1 },
  { id: 70, category: 'Atendimento', text: 'Cliente exaltado na loja.', answers: ['GRITAR TAMBÉM', 'MANTER A CALMA E OUVIR', 'CHAMAR SEGURANÇA LOGO'], correctIndex: 1 },
  { id: 71, category: 'Atendimento', text: 'Colega de trabalho atendendo.', answers: ['ATROPELAR A VENDA', 'RESPEITAR A VEZ', 'DAR PALPITE ERRADO'], correctIndex: 1 },
  { id: 72, category: 'Atendimento', text: 'Loja vazia. O que fazer?', answers: ['ARRUMAR O SETOR', 'DORMIR NO SOFÁ', 'FICAR NO ZAP'], correctIndex: 0 },
  { id: 73, category: 'Atendimento', text: 'Cliente pergunta a densidade do colchão.', answers: ['"NÃO SEI"', 'EXPLICAR COM PROPRIEDADE', '"ISSO NÃO IMPORTA"'], correctIndex: 1 },
  { id: 74, category: 'Atendimento', text: 'Feedback do cliente.', answers: ['LEVAR PARA O PESSOAL', 'USAR PARA MELHORAR', 'IGNORAR'], correctIndex: 1 },
  { id: 75, category: 'Atendimento', text: 'Cliente quer falar com o gerente.', answers: ['DIZER QUE NÃO ESTÁ', 'CHAMAR O GERENTE', 'RESOLVER SOZINHO NA MARRA'], correctIndex: 1 },
  { id: 76, category: 'Atendimento', text: 'Cliente com crianças bagunceiras.', answers: ['XINGAR A CRIANÇA', 'TER PACIÊNCIA E FOCO', 'EXPULSAR DA LOJA'], correctIndex: 1 },
  { id: 77, category: 'Atendimento', text: 'Sondagem bem feita.', answers: ['FAZ VENDER O CERTO', 'PERDE TEMPO', 'IRRITA O CLIENTE'], correctIndex: 0 },
  { id: 78, category: 'Atendimento', text: 'Cliente diz: "Tá caro".', answers: ['"É CARO MESMO"', '"COMPARADO A O QUÊ?"', '"VAI NO VIZINHO ENTÃO"'], correctIndex: 1 },
  { id: 79, category: 'Atendimento', text: 'Finalização da venda.', answers: ['LARGAR O CLIENTE', 'ACOMPANHAR ATÉ A PORTA', 'VIRAR AS COSTAS'], correctIndex: 1 },
  { id: 80, category: 'Atendimento', text: 'Cliente ligou reclamando.', answers: ['DESLIGAR NA CARA', 'ANOTAR E RESOLVER', 'PASSAR PARA OUTRO'], correctIndex: 1 },
  { id: 81, category: 'Atendimento', text: 'Produto sem estoque.', answers: ['OFERECER SIMILAR', 'PERDER A VENDA', 'VENDER MESMO ASSIM'], correctIndex: 0 },
  { id: 82, category: 'Atendimento', text: 'Benefício da Cama Baú.', answers: ['NENHUM', 'ESPAÇO EXTRA', 'É MAIS BARATA'], correctIndex: 1 },
  { id: 83, category: 'Atendimento', text: 'Benefício das Molas Ensacadas.', answers: ['NÃO FAZ BARULHO', 'BALANÇA TUDO', 'É MAIS DURA'], correctIndex: 0 },
  { id: 84, category: 'Atendimento', text: 'Cliente não sabe o tamanho da cama.', answers: ['VENDER QUALQUER UMA', 'PEDIR PARA MEDIR', 'VENDER A MAIOR'], correctIndex: 1 },
  { id: 85, category: 'Atendimento', text: 'Abordagem por telefone.', answers: ['FALAR RÁPIDO DEMAIS', 'SORRIR AO FALAR', 'COMER ENQUANTO FALA'], correctIndex: 1 },
  { id: 86, category: 'Atendimento', text: 'Limpeza da loja.', answers: ['RESPONSABILIDADE DE TODOS', 'SÓ DA LIMPEZA', 'NÃO IMPORTA'], correctIndex: 0 },
  { id: 87, category: 'Atendimento', text: 'Etiqueta de preço.', answers: ['ESCONDIDA', 'VISÍVEL E CORRETA', 'RABISCADA'], correctIndex: 1 },
  { id: 88, category: 'Atendimento', text: 'Cliente vip/antigo.', answers: ['TRATAR COMO QUALQUER UM', 'CHAMAR PELO NOME', 'IGNORAR HISTÓRICO'], correctIndex: 1 },
  { id: 89, category: 'Atendimento', text: 'Sorriso no rosto.', answers: ['ABRE PORTAS', 'NÃO FAZ DIFERENÇA', 'PARECE FALSO'], correctIndex: 0 },
  { id: 90, category: 'Atendimento', text: 'Conhecimento do produto.', answers: ['ESSENCIAL', 'OPCIONAL', 'INÚTIL'], correctIndex: 0 },
  { id: 91, category: 'Atendimento', text: 'Cliente quer pagar no crediário.', answers: ['BUFAR DE RAIVA', 'EXPLICAR REGRAS CLARAMENTE', 'NEGAR ATENDIMENTO'], correctIndex: 1 },
  { id: 92, category: 'Atendimento', text: 'Promessa de entrega.', answers: ['CUMPRIR O COMBINADO', 'ATRASAR SEM AVISAR', 'INVENTAR DATA'], correctIndex: 0 },
  { id: 93, category: 'Atendimento', text: 'Cliente testando travesseiro.', answers: ['EM PÉ', 'DEITADO NO COLCHÃO', 'NA MÃO APENAS'], correctIndex: 1 },
  { id: 94, category: 'Atendimento', text: 'Argumento para colchão firme.', answers: ['"É DURO IGUAL PEDRA"', '"BOM PARA COLUNA"', '"É O MAIS BARATO"'], correctIndex: 1 },
  { id: 95, category: 'Atendimento', text: 'Cliente olhando vitrine.', answers: ['PUXAR PRA DENTRO', 'CONVIDAR PARA ENTRAR', 'BLOQUEAR A VISÃO'], correctIndex: 1 },
  { id: 96, category: 'Atendimento', text: 'Troca de produto.', answers: ['DIFICULTAR AO MÁXIMO', 'SEGUIR POLÍTICA DA LOJA', 'DIZER QUE NÃO PODE'], correctIndex: 1 },
  { id: 97, category: 'Atendimento', text: 'Venda de impermeabilização.', answers: ['NÃO MENCIONAR', 'OFERECER COMO PROTEÇÃO', 'EMPURRAR SEM AVISAR'], correctIndex: 1 },
  { id: 98, category: 'Atendimento', text: 'Cliente com pressa.', answers: ['ENROLAR', 'SER OBJETIVO', 'IGNORAR A PRESSA'], correctIndex: 1 },
  { id: 99, category: 'Atendimento', text: 'Colega precisa de ajuda.', answers: ['FINGIR QUE NÃO VIU', 'AJUDAR SE POSSÍVEL', 'RIR DO COLEGA'], correctIndex: 1 },
  { id: 100, category: 'Atendimento', text: 'Metas do mês.', answers: ['ESQUECER', 'ACOMPANHAR DIARIAMENTE', 'SÓ VER NO FINAL'], correctIndex: 1 },
  { id: 101, category: 'Atendimento', text: 'Objeção: "Vou falar com a esposa".', answers: ['"ELA MANDA EM VOCÊ?"', '"QUER LEVAR UMA FOTO?"', '"COMPRA LOGO"'], correctIndex: 1 },
  { id: 102, category: 'Atendimento', text: 'Postura ao sentar.', answers: ['JOGADO NA CADEIRA', 'ERETA E PROFISSIONAL', 'PÉS NA MESA'], correctIndex: 1 },
  { id: 103, category: 'Atendimento', text: 'Linguagem corporal.', answers: ['BRAÇOS CRUZADOS', 'ABERTA E RECEPTIVA', 'OLHANDO PRO CHÃO'], correctIndex: 1 },
  { id: 104, category: 'Atendimento', text: 'Tom de voz.', answers: ['GRITANDO', 'MUITO BAIXO', 'CLARO E CALMO'], correctIndex: 2 },
  { id: 105, category: 'Atendimento', text: 'Cliente idoso.', answers: ['FALAR GÍRIAS', 'PACIÊNCIA E CLAREZA', 'APRESSAR'], correctIndex: 1 },
  { id: 106, category: 'Atendimento', text: 'Cliente quer "só o mais barato".', answers: ['MOSTRAR SÓ O RUIM', 'MOSTRAR CUSTO-BENEFÍCIO', 'DESDENHAR'], correctIndex: 1 },
  { id: 107, category: 'Atendimento', text: 'Estoque no sistema.', answers: ['CONFIAR CEGAMENTE', 'CONFERIR FÍSICO SE POSSÍVEL', 'CHUTAR QUE TEM'], correctIndex: 1 },
  { id: 108, category: 'Atendimento', text: 'Venda casada (Ilegal).', answers: ['PRATICAR SEMPRE', 'EVITAR / NÃO FAZER', 'DISFARÇAR'], correctIndex: 1 },
  { id: 109, category: 'Atendimento', text: 'Motivação diária.', answers: ['RECLAMAR DE TUDO', 'FOCO NA SOLUÇÃO', 'ESPERAR A HORA PASSAR'], correctIndex: 1 },
  { id: 110, category: 'Atendimento', text: 'Pós-venda.', answers: ['LIGAR PARA SABER SE GOSTOU', 'SUMIR DO MAPA', 'BLOQUEAR O CLIENTE'], correctIndex: 0 },
];
